ignored:
  - DL4006
  - DL3048 # Invalid label key.
  # - DL3018 # Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
  - DL3016 # Pin versions in npm. Instead of `npm install <package>` use `npm install <package>@<version>`
